apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-task
spec:
  params:
    - name: message    
  steps:
    - name: build-sources
      image: registry.redhat.io/ubi7/ubi-minimal
      script: |
        echo "$(params.message)"
