---
- name: get info of VM
  hosts: localhost
  tasks:
    - name: get vm info from openstack
      os_server_info:
        auth:
          auth_url: https://rhos-d.infra.prod.upshift.rdu2.redhat.com:13000/v3
          username: "{{ lookup('env','OS_USERNAME') }}"
          password: "{{ lookup('env','OS_PASSWORD') }}"
          project_name: psi-pipelines
        filters:
          name: "{{ lookup('env','VM_NAME') }}"
      register: result
    - debug:
        msg: "{{ result.openstack_servers }}"