---
# - name: Install tkn cli on RHEL
#   hosts: test-host
#   tasks:
#     - name: Install tkn cli on RHEL using yum
#       yum:
#         name: openshift-pipelines-client-0.9.0-2.el8.x86_64
#         state: present
#       become: yes
#       become_method: sudo
- name: Install tkn cli on RHEL
  hosts: test-host
  tasks:
    - name: Download the cli on RHEL VM
      get_url:
        url: https://github.com/tektoncd/cli/releases/download/v0.10.0/tektoncd-cli-0.10.0_Linux-64bit.rpm
        dest: /home/cloud-user/workspace/tektoncd-cli-0.10.0_Linux-64bit.rpm
    - name: Install tkn cli on RHEL using yum
      yum:
        name: /home/cloud-user/workspace/tektoncd-cli-0.10.0_Linux-64bit.rpm
        state: present
      become: yes
      become_method: sudo