---
- name: Run release test on RHEL vm
  hosts: rhel
  tasks:
    - name: clone the release tests repository
      git:
        repo: https://github.com/VeereshAradhya/release-tests.git
        dest: /home/cloud-user/workspace/release-tests
        version: poc-demo
    # - name: login to openshift using oc
    #   shell:
    #     cmd: oc login -u kubeadmin -p {{ lookup('env','OC_PASSWORD') }} {{ lookup('env','OC_SERVER_ADDRESS') }}  --insecure-skip-tls-verify=true
    #   shell:
    #     cmd: gauge run --env "test" --log-level=debug  --verbose specs/
    #     chdir: /home/cloud-user/workspace/release-tests
    # - name: run cli tests
    #   shell:
    #     cmd: gauge run --env "test" --log-level=debug --verbose specs/cli/pipelines-e2e.spec
    #     chdir: /home/cloud-user/workspace/release-tests